FROM golang:1.21 AS deps
WORKDIR /build
COPY app/go.mod app/go.sum ./
RUN go mod download

FROM golang:1.21 AS builder
WORKDIR /build
COPY --from=deps /build/go.mod /build/go.sum ./
RUN go mod download
COPY app/* .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o myapp .

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=builder --chown=nonroot:nonroot /build/myapp .
USER nonroot
EXPOSE 8080
CMD ["./myapp"]
